export const ADD_STORIES = 'ADD_STORIES';
export const ADD_STORIES_REQUEST = 'ADD_STORIES_REQUEST';
export const ADD_STORIES_FAILED = 'ADD_STORIES_FAILED';
export const INCRASE_LIMIT = 'INCRASE_LIMIT';
export const DECRASE_LIMIT = 'DECRARE_LIMIT';
